name: elangelangelang
favicon: null
layout_spectrum: 0.263
typography_spectrum: 0.55401
title: Elang by Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eeeced'
    - '#00c5d8'
    - '#0087a4'
    - '#d09b8b'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
